### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -i 3 -w -S *.po,./share/patchfiles,./libs  -L ba,buss,busses,doubleclick,hsi,ontop,seh,sur,ue`

### CODE REVIEW

**Comment by luzpaz** [comment]
ping @pauldavisthefirst

**Comment by pauldavisthefirst** [comment]
Sorry I haven't responded to this PR.

The problem with big PRs like this is that we need to review every single change before accepting (or rejecting) it. Paradoxically, a series of tiny PRs would probably get handled faster than this one big one. Although I have no reason to suspect any bad intent on your part, we still need to review all the changes because sometimes (rarely!) things are not quite what they seem.

**Comment by luzpaz** [comment]
@pauldavisthefirst i get it. These are also kind of annoying PRs, tbh. But they keep the code clean and documentation (generated from the code clean as well). I also sometimes find typos that are actually are bugs. LMK if you need me to further separate this PR. I'd be cool with that.

**Comment by BrunoVernay** [comment]
There could be some kind of commit check automation to run the `codespell ...` command and detect the typo before they are committed !

**Comment by luzpaz** [comment]
Pushed a few more typos I've found  4067e50

**Comment by luzpaz** [comment]
Closing in favor of #664

**Comment by luzpaz** [comment]
> There could be some kind of commit check automation to run the `codespell ...` command and detect the typo before they are committed !

@BrunoVernay this is possible with github actions. See https://github.com/FreeCAD/FreeCAD/commit/c7cf9b25dfc6ec4fbbba8db7adfd7eb54be105fa

**Comment by pauldavisthefirst** [comment]
Just to be clear, we do not use github for anything except accepting PRs and providing a public readable repository. That's not going to change.

However, it can be done using the basic features of git (hooks). Sometime in the next few months, the ardour.org website will be seeing a major upgrade, and potentially after that we could consider adding a hook for this.

**Pull request closed without merging**
