### PR TITLE
Reduce reliance on Boost libraries

### PR DESCRIPTION
**Pull request by aledomu**

### CODE REVIEW

**Comment by pauldavisthefirst** [comment]
Repeating myself ... because of our multiple code bases, several of the commits above need to be in the form of sed(1) script or equivalent, so that the changes can be run multiple times.

**Comment by x42** [comment]
Then again a `sed` script won't help for e.g. ` Replace boost::noncopyable with C++11 deleted copy constructors `

various derivative projects have additional classes

**Comment by aledomu** [comment]
> Repeating myself ... because of our multiple code bases, several of the commits above need to be in the form of sed(1) script or equivalent, so that the changes can be run multiple times.

I thought these changes would be more or less self-contained. Which ones do not need to be sed scripts? I can isolate those.

> Then again a sed script won't help for e.g. Replace boost::noncopyable with C++11 deleted copy constructors
>
> various derivative projects have additional classes

Do you mean subclasses? The non-copyable behaviour is inherited with deleted copy constructors as well.

**Comment by aledomu** [comment]
Regexes for some of the commits:

* Replace boost::unordered_map with std::unordered_map:
  * `s/boost::unordered_map/std::unordered_map/g`
  * `s/#include <boost\/unordered_map.hpp>\n//g`
* Replace BOOST_FOREACH with standard for-each:
  * `s/BOOST_FOREACH \((.*),(.*)/for \(\1 :\2/g`
  * `s/BOOST_FOREACH\((.*),(.*)/for \(\1 :\2/g`
  * `s/#include <boost\/foreach.hpp>\n//g`
* Replace BOOST_STATIC_ASSERT with static_assert:
  * `s/BOOST_STATIC_ASSERT/static_assert/g`
  * `s/#include <boost\/static_assert.hpp>\n//g`
* Replace boost::tuple with std::tuple:
  * `s/boost::tuple/std::tuple/g`
  * `s/#include <boost\/tuple\/tuple.hpp>\n//g`
  * `s/#include <boost\/tuple\/tuple_comparison.hpp>\n//g`
* Replace boost::math::isnormal with std::isnormal:
  * `s/boost::math::isnormal/std::isnormal/g`
  * `s/#include <boost\/math\/special_functions\/fpclassify.hpp>\n//g`
* Replace boost::container::set with std::set:
  * `s/boost::container::set/std::set/g`
  * `s/#include <boost\/container\/set.hpp>\n//g`

**Comment by x42** [comment]
I've scripted the  parts of this which also relevant for derivative projects,
and cherry-picked the other commits.

The result 9.0-pre0-267-g74c4ca3e52,  I hope I caught everything!

**Comment by aledomu** [comment]
Most of it is in, but there are some leftovers. I rebased and resolved conflicts so you can inspect and decide how to incorporate the few remaining changes.

**Pull request closed without merging**
