### PR TITLE
Add note name to number converter

### PR DESCRIPTION
**Pull request by ngeiswei**
Useful for the midi list editor (in a forthcoming PR).

### CODE REVIEW

**Comment by x42** [comment]
What is the eventual use-case for this function? Does it allow user-entry?

Note that ParameterDescriptor::midi_note_name() is translatable. I suppose you should compare against the gettext string and UTF-8  e.g.  Do, Do ♯, Ré, Ré ♯ ... for French.

**Comment by ngeiswei** [comment]
The use case is #322 (can edit the note name in the midi list editor, not just the note number).

As for the translation, I wonder who wants that, but if you think it's important I can have it support it as well.

**Comment by x42** [comment]
German users want "H" instead of "B" and some French composers and musicians asked for solfege last year: mainly for the verbose cursor in the editor and plugin controls.

I don't know if it make sense for  a tracker interface on a grid, but display and entry should be consistent.

If the list editor displays "Do" don't expect a user to enter "C". Then there's Japanese ハ, too (though the Ardour translation has not caught up there, yet)

Maybe the exiting method needs `midi_note_name(bool translate)` and prefill the entry?

**Comment by ngeiswei** [comment]
Fair enough. I think you are right about offering optional midi note translation (i.e. when the language setting is different than English). And yes we probably want pre-calculate a bijective map:
```
note name <-> note number
```
rather than hardcode an English note name parser.

I'll study how automatic translation works in Ardour and get back.

**Comment by trebmuh** [comment]
> As for the translation, I wonder who wants that, but if you think it's important I can have it support it as well.

I do. And basically, pretty much most of the musician from the latin world would are not using the A, B, C ... notation.

**Comment by ngeiswei** [comment]
Don't merge just yet, it needs more testing...

**Comment by ngeiswei** [comment]
It's annoying I can't test it for other languages than English. I can change the OS language, all my programs seem to be translated but ardour isn't. I think it should work of course but I can't test...

**Comment by pauldavisthefirst** [comment]
you probably need to use ./waf configure with the --nls option

**Comment by ngeiswei** [comment]
Does not work either. I should note that it works on the pre-compiled version of Ardour provided by Ubuntu Studio 16.10 (although the sharp symbols are displayed as ?? - for the French language). Maybe I'm missing some library, although looking at the output of `./waf configure --nls` doesn't reveal anything obvious.

**Comment by ngeiswei** [comment]
Oh, I had the good idea to install instead of running `ardev` and it works! Well the i18n works, my code actually has some problems, so don't merge just yet...

**Comment by ngeiswei** [comment]
Actually, I'm observing the same problem on the master, being that instead of having "Sol" being display (the French translation of "G"), I see "Note|Sol". If I switch back to English, then it properly displays "G" with the "Note|" prepended to it.

**Comment by ngeiswei** [comment]
I'm no i18n expert but I suspect it is a translation error. See for instance
https://github.com/Ardour/ardour/blob/master/libs/ardour/po/fr.po#L1679
https://github.com/Ardour/ardour/blob/master/libs/ardour/po/de.po#L1697
you may observe that the context `Note|` is still present in the French translation but missing in the German one.

**Comment by ngeiswei** [comment]
Just to be clear, don't merge just yet, there's another issue beside i18n.

**Comment by ngeiswei** [comment]
AFAIK, you can merge. The i18n is a different issue, IMO.

#322 has been tested as well can be merged right after, AFAIK.

**Comment by ngeiswei** [comment]
Any news on this? I'm gonna need it soon.

**Comment by x42** [comment]
I'll need to double check `boost::algorithm::ilexicographical_compare` availability, but this looks fine otherwise.

**Comment by pauldavisthefirst** [comment]
can't see a reason why, given that we know the note name is a latin alpha, strcasecmp() isn't adequate.

what am i missing?

**Comment by ngeiswei** [comment]
Because if `translate` is set to true (the default) in `ParameterDescriptor::midi_note_name (const uint8_t b, bool translate)` then the keys in `name2num` are translated, so they could be anything, not just latin.

**Comment by ngeiswei** [comment]
And of course `boost::algorithm::ilexicographical_compare` is case insensitive. So to sum up, the reasons are

1. Supports i18n
2. Is case insensitive

**Comment by ngeiswei** [comment]
Anything preventing this PR to be merged?

**Comment by x42** [comment]
Why does the map have to be lexically sorted at all?

**Comment by ngeiswei** [comment]
It doesn't have to be *lexically* sorted, but it has to be sorted in a way that is case insensitive, which `boost::algorithm::ilexicographical_compare` offers. The reason is has to be sorted at all, lexically or not, is so the note name can be mapped to the note number, see `ParameterDescriptor::build_midi_name2num` and `ParameterDescriptor::midi_note_num`.

**Comment by x42** [comment]
I must still be missing something. I don't see why sorting is needed. Both note numbers and note names are unique and the map is isomorph.   `std::map<std::string, uint8_t>`  should suffice.

**Comment by ngeiswei** [comment]
Case-insensitive allows the user to enter "f4" and be recognized as "F4". For having used it, I can tell that it is really convenient.

**Comment by ngeiswei** [comment]
Now if you don't want to depend on `boost::algorithm::ilexicographical_compare` I can certainly rewrite the code to do without it, it's more elegant that way.

**Comment by ngeiswei** [comment]
Well, I can always reimplement `is_ilexicographical_compare` :-) ;-)

**Comment by x42** [comment]
So `midi_note_num (const std::string& name)` should convert the string to lower-case before lookup, shouldn't it?

just `boost::to_lower()` when building the map and `name2num.find(boost::to_lower(name))`

**Comment by ngeiswei** [comment]
If `is_ilexicographical_compare` is used there is no need to convert the string to lower-case before look-up, the look-up itself will be case-insensitive.

Do you want me to recode it as to not rely on `boost::algorithm::ilexicographical_compare`?

**Comment by ngeiswei** [comment]
Anyway, you did convince me, using `boost::to_lower()` when building the map and performing the look-up is simpler than using `is_ilexicographical_compare`, certainly in terms of LOC, so I'll go with that.

**Comment by ngeiswei** [comment]
Closing, will squash into a single commit.

**Pull request closed without merging**
