### PR TITLE
Update zh.po

### PR DESCRIPTION
**Pull request by YQ-YSY**
translate english -> chinese all done.

### CODE REVIEW

**Comment by pauldavisthefirst** [comment]
Thanks! Any chance you could also update libs/ardour/po/zh.po ?

**Comment by YQ-YSY** [comment]
Sorry I'm beginner for github, I don't know what's the different between libs/ardour/po/zh.po and gtk2_ardour/po/ ? I think they are a same file... am I wrong? And, how to get the latest po soure file for the latest Ardour version? (Some new word added in latest Ardour version) I'll fix my mistake.

**Comment by YQ-YSY** [comment]
I‘m checking my zh.po files, compare with de.po, add the missing parts...
I found lots of comments in po flie (th lines start with # ) are different,
For example: 
#: editor_actions.cc:451 msgid "Zoom Focus Right" ----in de.po file
#: editor_actions.cc:435 msgid "Zoom Focus Right" ----in zh.po file
The munber is different. Is it need to fix?

**Comment by pauldavisthefirst** [comment]
This file should explain everything: https://github.com/Ardour/ardour/blob/master/TRANSLATORS

Let me know if you have specific questions. The .po files are only up to date AFTER running ./waf i18n_pot

**Comment by YQ-YSY** [comment]
Thank you. I download ZIP, unzip and run ./waf i18n_pot, but it shows:
This tarball was not created correctly - it is missing libs/ardour/revision.cc
What should I do?

**Comment by pauldavisthefirst** [comment]
Did you run

./waf configure

before ./waf i18n_pot

?

**Comment by YQ-YSY** [comment]
Run ./waf configure, show the same message:
This tarball was not created correctly - it is missing libs/ardour/revision.cc

Sorry...I don't know... I'm not a programmer, 
but I want to help more Chinese people use open source software.
what can I do only translation and write some tutorial.

Can you tell me more operating steps about how to get po?

**Comment by prokoudine** [comment]
Could you please try this on git repository checkout? :)

**Comment by YQ-YSY** [comment]
Thank you prokoudine, here is I'm trying:
git init
git clone http://github.com/Ardour/ardour  ##### I found this command today, thanks your reply。
cd ardour
./waf configure
Checking for boost library >= 1.39 : too old ##### So I install libboost1.58-dev
Checking for alsa: not found.  ##### So I install libasound2-dev 
Checking for 'sndfile' >= 1.0.18 : not found  ##### So I install libsndfile1-dev
Checking for 'libcurl' >= 7.0.0 : not found  ##### So I install libcurl4-gnutls-dev
Checking for 'liblo' >= 0.26 : not found  ##### So I install liblo-dev
Checking for 'taglib' >= 1.6 : not found  ##### So I install libtag1-dev
Checking for 'vamp-sdk' >= 2.1 : not found  ##### So I install vamp-plugin-sdk
Checking for 'rubberband' : not found  ##### So I install librubberband-dev
Checking for  sndfile RF64=>RIFF support : Not found, no RF64-to-WAV support 
Checking for clang                                   : no 
Checking for 'fftw3f'                                : not found 
The configuration failed
##### After I install 8 package, I stop at here,
I don't know what I should install, I can not find anything about them in Google.

Sorry, I just want to translate the language of GUI, not programme for Ardour.
If you can build the new PO file, can you send it to me? So my work is more easy.
Please only create new PO files, as no existing translation for my language (delete two old zh.po files).
You can send these new two zh.po files to my email YQ-YSY@163.com. 
I think other country Ardour user, not programmer, they want to get an esay way to translate, too.

Thanks for your help again.

**Comment by prokoudine** [comment]
1. You didn't have to do 'git init' at all. Now you have git inside git. Please don't do it :) Just run 'git clone http://github.com/Ardour/ardour' or, better yet, fork repository on GitHub and clone your fork.

2. You need to install fftw3 headers. I'm guessing you are on either Debian or Ubuntu. The package is called libfftw3-dev.

3. "Sorry, I just want to translate the language of GUI, not programme for Ardour." -- I'm not sure what you meant here :)

4. "If you can build the new PO file, can you send it to me? So my work is more easy." -- How good will your translation be, if you translate software without checking how it looks like by looking at the results? Can you at least install a fresh nightly build, so that we would be on the same page?

5. "I think other country Ardour user, not programmer, they want to get an esay way to translate, too." -- well, I'm not a programmer either, just a translator, same as you.

**Comment by x42** [comment]
You do not need to program (write source code) to translate,
but to test translations and keep up with changes, you basically need to compile Ardour so that you can run it.

Ardour has a lot of dependencies. However on many linux distros its easy to automatically get those.
eg. on debian/ubuntu   `sudo apt-get build-dep ardour`  no need to manually install them one by one.

**Comment by YQ-YSY** [comment]
Thank you x42 & prokoudine, 
sudo apt-get build-dep ardour --very useful, finally I get two new pot files:
./gtk2_ardour/gtk2_ardour4.pot  #### It obviously can be used for create my ./gtk2_ardour/po/zh.po
but,
./libs/gtkmm2ext/gtkmm2ext3.pot #### Is it for ./libs/ardour/po/zh.po? It seems too small, only include 29 items, the old po file has 624 or 746 items. Is it right?

And, can you tell me how to compile Ardour?
After I run "make" (without any arguments),  'build' finished successfully (19m38.067s)
But I run "make install", make: *** No rule to make target 'install'.

And then I follow this page http://www.linuxmao.org/Ardour+4+Compilation
get a lot of red errors after run ./waf install 
Build failed
Traceback (most recent call last):
  File "/home/abc/Ardour_workshop/Ardour_GitHub/ardour/.waf-1.6.11-dd5a1e1fe94b4aa17a652d5945db5927/waflib/Task.py", line 125, in process
    ret=self.run()
...

**Comment by pauldavisthefirst** [comment]
did you run "./waf install" as root?

anyway, no need to do the install step (and probably not sensible to do it,
either).

to run the program after the build, do this:

   cd gtk2_ardour
   ./ardev

(assuming you are already in the folder/directory at the top of the source
code tree)

thanks for your efforts on this. we look forward very much to your
translation!

**Comment by YQ-YSY** [comment]
Yeah,  I run./waf i18n_pot again get ./libs/ardour/ardour4.pot now.
OK, two PO files solved. 
And run ./ardev in gtk2_ardour, Ardour is work!
Thank you for your patience.
I will do my best to translate Ardour to Chinese,
and I'm translating  Ardour 4 BEGINNER'S TUTORIAL,
http://wiki.ubuntu.org.cn/Ardour4_%E5%88%9D%E5%AD%A6%E8%80%85%E6%95%99%E7%A8%8B_03_%E7%BC%96%E8%BE%91%E4%BC%9A%E8%AF%9D
I hope that more and more people like to use Ardour.
Thanks again.

**Comment by YQ-YSY** [comment]
Sorry I back again.
Run ./ardev Ardour is still work in English, not change language.
I already have run ./waf i18n_mo, and there is zh.mo file in gtk2_ardour/po/
The same MO file at /usr/share/ardour4/locale/zh/LC_MESSAGES/gtk2_ardour4.mo (renamed) work well in old version.
What should I do？Is it need any arguments?

**Comment by YQ-YSY** [comment]
there are 2 clerical errors in the source /libs/ardour/ardour4.pot, please fix them.

(1)
Session: you can't use that location for session start/end)
--missing left parenthesis: ( 

(2)
Please remove extra subdirs to reduce possible filename ambiguties. 
---ambiguties should be  ambiguities (missing i )

**Comment by pauldavisthefirst** [comment]
manually rebased and pushed to master. thanks for your work! We hope you will stay around to the ZH translation up to date for future releases.

**Pull request closed without merging**
