### PR TITLE
Align libaaf structure with upstream, and update + fixes

### PR DESCRIPTION
**Pull request by nphilipp**
This changes `update_libaaf.sh`, so it keeps the same file structure as the libaaf upstream, mainly so header files can be included the same way if you use the bundled lib or an external version.

Also, it updates the bundled libaaf to v0.5 + a constness fix, fixes detecting the external libaaf library and uses `g_path_get_basename()` instead of `g_basename()`, which has been deprecated for a long time.

### CODE REVIEW

**Comment by x42** [comment]
All these changes will be lost when we run https://github.com/Ardour/ardour/blob/master/tools/update_libaaf.sh

**Review by x42 — COMMENTED** [review]
I think upstream should provide a pkg-config file

**Comment by x42** [comment]
Has #854 addressed all this (except the pkg-config part)?

**Comment by x42** [comment]
pkg-config is now available upstream:  https://github.com/agfline/LibAAF/issues/24

**Comment by dvzrv** [comment]
Hi! I'd like to see (parts of this change) happening, as using the upstream provided libaaf currently fails due to headers being used from the wrong location in the bundled version:

```
[1196/1227] Compiling session_utils/common.cc
10:50:26 runner ['/usr/bin/g++', '-I/build/ardour/src/ardour', '-march=x86-64', '-mtune=generic', '-O2', '-pipe', '-fno-plt', '-fexceptions', '-Wp,-D_FORTIFY_SOURCE=2', '-Wformat', '-Werror=format-security', '-fstack-clash-protection', '-fcf-protection', '-Wp,-D_GLIBCXX_ASSERTIONS', '-g', '-ffile-prefix-map=/build/ard
our/src=/usr/src/debug/ardour', '-flto=auto', '-I/usr/include/qm-dsp', '-DHAVE_RF64_RIFF', '-DCOMPILER_INT128_SUPPORT', '-DWAF_BUILD', '-DNDEBUG', '-fshow-column', '-O3', '-fomit-frame-pointer', '-ffast-math', '-fstrength-reduce', '-pipe', '-DARCH_X86', '-mmmx', '-msse', '-mfpmath=sse', '-DUSE_XMMINTRIN', '-DBUILD_SSE
_OPTIMIZATIONS', '-DLXVST_64BIT', '-Wall', '-Wpointer-arith', '-Wcast-qual', '-Wcast-align', '-Wno-unused-parameter', '-DBOOST_SYSTEM_NO_DEPRECATED', '-DBOOST_BIND_GLOBAL_PLACEHOLDERS', '-D_ISOC9X_SOURCE', '-D_LARGEFILE64_SOURCE', '-D_FILE_OFFSET_BITS=64', '-DPROGRAM_NAME="Ardour"', '-DPROGRAM_VERSION="8"', '-std=c++1
1', '-DBOOST_NO_AUTO_PTR', '-DBOOST_BIND_GLOBAL_PLACEHOLDERS', '-Woverloaded-virtual', '-Wno-unused-local-typedefs', '-D__STDC_LIMIT_MACROS', '-D__STDC_FORMAT_MACROS', '-DCANVAS_DEBUG', '-DBOOST_ERROR_CODE_HEADER_ONLY', '-fvisibility=default', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-p
thread', '-Isession_utils', '-I../session_utils', '-Ilibs', '-I../libs', '-Ilibs/ctrl-interface/control_protocol', '-I../libs/ctrl-interface/control_protocol', '-Ilibs/ardour', '-I../libs/ardour', '-Ilibs/midi++2', '-I../libs/midi++2', '-Ilibs/evoral', '-I../libs/evoral', '-Ilibs/temporal', '-I../libs/temporal', '-Ili
bs/audiographer', '-I../libs/audiographer', '-Ilibs/audiographer/src', '-I../libs/audiographer/src', '-Ilibs/ptformat', '-I../libs/ptformat', '-Ilibs/pbd', '-I../libs/pbd', '-Ilibs/lua', '-I../libs/lua', '-Ilibs/zita-resampler', '-I../libs/zita-resampler', '-Ilibs/zita-convolver', '-I../libs/zita-convolver', '-I/usr/i
nclude/freetype2', '-I/usr/include/libpng16', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib/glib-2.0/include', '-I/usr/include/sysprof-6', '-I/usr/include/glibmm-2.4', '-I/usr/lib/glibmm-2.4/include', '-I/usr/include/sigc++-2.0', '-I/usr/lib/sigc++-2.0/include', '-I/usr/include/giomm-2.4', '-I/usr/
lib/giomm-2.4/include', '-I/usr/include/libmount', '-I/usr/include/blkid', '-I/usr/include/libxml2', '-I/usr/include/taglib', '-I/usr/include/lilv-0', '-I/usr/include/sord-0', '-I/usr/include/serd-0', '-I/usr/include/sratom-0', '-I/usr/include/zix-0', '-I/usr/include/raptor2', '-I/usr/include/suil-0', '-I/usr/include/
libusb-1.0', '-I/build/ardour/src/ardour/build', '-DINTERNAL_SHARED_LIBS=1', '-DUSE_EXTERNAL_LIBS=1', '-DHAVE_ALSA=1', '-DHAVE_PULSEAUDIO=1', '-DHAVE_GLIB=1', '-DHAVE_GTHREAD=1', '-DHAVE_GLIBMM=1', '-DHAVE_SNDFILE=1', '-DHAVE_GIOMM=1', '-DHAVE_CURL=1', '-DHAVE_ARCHIVE=1', '-DHAVE_LO=1', '-DHAVE_TAGLIB=1', '-DHAVE_VAMP
SDK=1', '-DHAVE_VAMPHOSTSDK=1', '-DHAVE_RUBBERBAND=1', '-DHAVE_USB=1', '-DHAVE_RUBBERBAND_3_0_0=1', '-DEXPORT_VISIBILITY_HIDDEN=0', '-DENABLE_NLS=1', '-DLXVST_SUPPORT=1', '-DVST3_SUPPORT=1', '-DPTFORMAT=1', '-DUSE_FUTEX_SEMAPHORE=1', '-DFPU_AVX512F_SUPPORT=1', '-DFPU_AVX_FMA_SUPPORT=1', '-DCONFIG_ARCH="x86_64"', '-DHA
VE_TOOLS_SANITY_CHECK=1', '-DHAVE_LIBFLUIDSYNTH=1', '-DHAVE_HIDAPI=1', '-DHAVE_LIBLTC=1', '-DHAVE_FFTW3F=1', '-DHAVE_AUBIO=1', '-DHAVE_AUBIO4=1', '-DHAVE_LIBAAF=1', '-DHAVE_XML=1', '-DHAVE_SIGCPP=1', '-DHAVE_EXECINFO=1', '-DHAVE_POSIX_MEMALIGN=1', '-DHAVE_GETMNTENT=1', '-DHAVE_LOCALTIME_R=1', '-DHAVE_CPPUNIT=1', '-DHA
VE_CONTROL_PROTOCOL=1', '-DHAVE_MIDI_SURFACE=1', '-DHAVE_WEBSOCKETS=1', '-DHAVE_PANGOMM=1', '-DHAVE_CAIROMM=1', '-DHAVE_JACK=1', '-DHAVE_JACK_METADATA=1', '-DHAVE_JACK_PORT_RENAME=1', '-DHAVE_LRDF=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_LV2=1', '-DHAVE_LV2_1_10_0=1', '-DHAVE_LV2_1_17_2=1', '-DHAVE_LV2_1_18_6=1', '-DHAVE_SE
RD=1', '-DHAVE_SORD=1', '-DHAVE_SRATOM=1', '-DHAVE_LILV=1', '-DHAVE_SUIL=1', '-DLV2_SUPPORT=1', '-DLV2_EXTENDED=1', '-DHAVE_OGG=1', '-DHAVE_FLAC=1', '-DHAVE_FFTW35F=1', '-DUSE_RUBBERBAND=1', '-DCURRENT_SESSION_FILE_VERSION=7002', '-DHAVE_SYS_VFS_H=1', '-DHAVE_SYS_STATVFS_H=1', '-DHAVE_UNISTD=1', '-DHAVE_BOOST_SCOPED_P
TR_HPP=1', '-DHAVE_BOOST_PTR_CONTAINER_PTR_LIST_HPP=1', '-DHAVE_GTKMM=1', '-DHAVE_GTK=1', '-DHAVE_BOOST_SHARED_PTR_HPP=1', '-DHAVE_BOOST_FORMAT_HPP=1', '-DHAVE_LV2_1_0_0=1', '-DHAVE_CAIRO=1', '-DHAVE_X11=1', '-DHAVE_PANGOFT2=1', '-DHAVE_FONTCONFIG=1', '-DHAVE_READLINE=1', '-DHAVE_DBUS=1', '-DVERSIONSTRING="8.2.0"', '-
DUTILNAME="ardour8-new_session"', '-DDATA_DIR="/usr/share/ardour8"', '-DCONFIG_DIR="/etc"', '-DLOCALEDIR="/usr/share/ardour8/locale"', '-DPACKAGE="ARDOURUTILS"', '../session_utils/common.cc', '-c', '-o/build/ardour/src/ardour/build/session_utils/common.cc.9.o']
../session_utils/new_aaf_session.cc:49:10: fatal error: aaf/libaaf.h: No such file or directory
   49 | #include "aaf/libaaf.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
```

Furthermore, the package is searched for by the name of `aaf` through pkgconfig, which does not exist (upstream exposes it as `libaaf`). This is addressed by explicitly looking for a library (of the name `aaf`) in this PR.

**Comment by x42** [comment]
We specifically re-arranged it to conform to Ardour's source tree structure with include files in a common subfolder

**Pull request closed without merging**
