### PR TITLE
Https

### PR DESCRIPTION
**Pull request by kiilerix**
Avoid MITM and other problems from using plain http.

The build scripts would perhaps also be important to update.

### CODE REVIEW

**Comment by kiilerix** [comment]
```
Oct 05 23:10:09 <las>   kiilerix: we have http -> https redirection turned on in nginx
Oct 05 23:10:16 <las>   kiilerix: no need for it in every URL
Oct 05 23:10:46 <x42>   except ping-back still uses http (since we cannot rely on certs with ardour binaries)
Oct 05 23:13:28 <kiilerix>      las, but server side redirection to https doesn't help much; in the attack scenario where someone can intercept and redirect connections, they can modify the http request to redirect to some rogue site or proxy the https away
Oct 05 23:13:38 <las>   kiilerix: fair enough
```
I maintain that everybody should use https everywhere (with few exceptions like localhost or very trusted private networks or where other higher level encryption is used). There might be places we the change isn't trivial, but that shouldn't prevent us from doing the right thing in other places.

**Comment by x42** [comment]
The problem is that we cannot rely that our official binaries can find certs on the target system. (some distributions have non-standard setup).

There is nothing to hide (no credentials, etc) on requests that Ardour makes and there is an additional benefit that our server load is reduced if no additional encryption is performed.

**Comment by x42** [comment]
I have no strong opinion about the README URLs, but all source-code URLs (incl PBD::open) should remain opt-in.

**Comment by kiilerix** [comment]
To the best of my knowledge, this PR is only proposing change of URLs that users will open in their web browser. If a users browser can't handle https, they really shouldn't try to connect to the internet. I thus don't see the relevance of the objection.

Every single unencrypted remote URL that Ardour uses / refers to is a a liability and tech debt. I guess it eventually will end up as a CVE and embarrassment. It will serve you (and us, your users) well to try to minimize that debt. This PR is one small step, that makes the remaining problem a bit more clear.

But regarding the **different** problem of changing **other** URLs to https:
I sympathize with the difficulty of integrating with system security infrastructure in a cross-platform binary. But it is something others have done before. And while not perfect, I think it will be a fine solution to fall back to bundled root certificates. And for connections back to your own servers, you could even "hardcode" the fingerprint.

**Comment by x42** [comment]
Point taken. rebased and merged as 7.0-96 74584db195 
I have split the last commit into smaller chunks, mainly because we have the general rule to not change library and UI code in the same commit.

**Pull request closed without merging**
