### PR TITLE
Show makeup gain in a-comp's inline rendering

### PR DESCRIPTION
**Pull request by johannes-mueller**
Is there a reason not to do it?

### CODE REVIEW

**Comment by x42** [comment]
Quick experiment on top of this patch to show the range -60 .. +10dBFS

https://gist.github.com/x42/030ecdcb697f20489826074832c20ce8

**Comment by johannes-mueller** [comment]
I like your experiment. It's good to have the lines at 0.0 dBFS clearly visible.

**Comment by x42** [comment]
@zamaudio  any opinions? reasons not to merge this?

**Comment by zamaudio** [comment]
Perhaps the makeup should not affect the graph when the plugin is bypassed.  Otherwise LGTM.

**Comment by johannes-mueller** [comment]
@zamaudio yeah, I missed that in the stereo version. Fixed in 265a879.

**Comment by johannes-mueller** [comment]
In the meantime it's more than just the makeup gain thing. It also adresses #7120.

If the channel strip is wide enough (≥100 px) we show the graph with a gain reduction meter bar overlay. If the width is <100px we switch to a view where only a output level and a gain reduction meter bar is shown.

In this meter bar mode we take the whole height for the inline display, that we are granted, which might be a little too much, but I think as for now, we can keep it.

**Comment by x42** [comment]
In narrow mode the gain-meters increases the height requirement. IIUC #7120 suggested a horizontal meter (about the same size as an inline-control)  to save vertical space.

**Comment by johannes-mueller** [comment]
Right. But #7120 raises more fundamental questions about the a-plugins. I will write to the dev mailing list when I'm back from my weekend trip.

**Comment by johannes-mueller** [comment]
Closed in favor of [PR 365](https://github.com/Ardour/ardour/pull/365)

**Pull request closed without merging**
