### PR TITLE
Update script documentation

### PR DESCRIPTION
**Pull request by Stemby**

### CODE REVIEW

**Comment by x42** [comment]
Thanks. I've applied the link-fix 6.3-228 e96c7e9b84.

There are 27 "README" files and all are effectively plain text, so I did not pick up the markdown change.

**Comment by keryell** [comment]
Just looking at the `README` file, what is actually the markup language used there?

**Comment by x42** [comment]
None, just plain text

**Comment by keryell** [comment]
Ah, thanks.
In `share/scripts/README` there are some `^_`, `^__`, `^_-*.lua` so I thought it was a mark-up language... :-)

**Comment by x42** [comment]
Those are file-name pattern.

**Comment by Stemby** [comment]
The `^` character isn't part of a filename pattern.

**Comment by x42** [comment]
it's a [glob](https://en.wikipedia.org/wiki/Glob_(programming)).  here `^` matches the beginning of a file's name (similar to regular expression boundary match)

https://github.com/Ardour/ardour/blob/f3fbb96d6a2b49cd305d7ca3af5601352fa49104/share/scripts/wscript#L12

**Pull request closed without merging**
