### PR TITLE
Support region moving and resizing in list editor

### PR DESCRIPTION
**Pull request by ngeiswei**
If the region is moved or resized the list editor gets refreshed accordingly.

### CODE REVIEW

**Comment by pauldavisthefirst** [comment]
Is this still relevant?

**Comment by ngeiswei** [comment]
The problem is still there, yes, as of reversion f744b5fc12 .

**Comment by ngeiswei** [comment]
@pauldavisthefirst, would you like me to rebase?

**Comment by pauldavisthefirst** [comment]
yes please.

**Comment by ngeiswei** [comment]
Rebased and tested.

**Comment by ngeiswei** [comment]
Just a reminder that this PR has been rebased and tested (in case you wish to have it make it into 6.0).

**Comment by pauldavisthefirst** [comment]
manually rebased and merged. thanks!

**Pull request merged**
