### PR TITLE
Use HTTPS instead of HTTP

### PR DESCRIPTION
**Pull request by BrunoVernay**
The tutorial is a redirect to a http link, but still. it does not hurt.
The "pingback"  should not be very risky, but better safe than sorry.
Only the local video-server stays in plain HTTP.

### CODE REVIEW

**Comment by abulvenz** [comment]
Now that you want to change it:
https://ardour.org/donate redirects permanently to https://community.ardour.org/donate

**Comment by x42** [comment]
At least for URLs that ardour loads itself (pingback) we cannot rely on SSL.
Ardour binries ship libcurl and NSS, and then there is custom code to lookup certs which are installed system-wide (not bundled).

Depending on the distro, this may or may not work.

**Comment by BrunoVernay** [comment]
OK: I keep HTTP for Ardour's internaly handled HTTP requests.
I integrated the permanent redirect.

**Comment by pauldavisthefirst** [comment]
I've manually updated the donate URL.

**Pull request closed without merging**
