### PR TITLE
Updated Swedish language

### PR DESCRIPTION
**Pull request by Umeaboy**
Signed-off-by: Kristoffer Grundström <hamnisdude@gmail.com>

### CODE REVIEW

**Comment by Umeaboy** [comment]
Is there anyone that can merge this? Just curious.

**Comment by mojofunk** [comment]
Thanks for this translation update. Yes there there are several people that can merge PR's and do so regularly. How long it may take is variable and dependent on many factors but you can expect further feedback in a within a few days.

**Comment by jplloyd** [comment]
Some comments from a native speaker:

When things can translate to multiple different words, be sure that the terms you use are the correct ones, both semantically and contextually. Same thing applies to the reverse scenario, if a term you are translating can have multiple different meanings. Here "Config" is translated to (one ambiguous way of saying) "Configure", whereas in the context of the string it actually means "Configuration / Setup".

Your translations of "Range" uses the term for effective range of e.g. transceivers, like a cellphone tower, rather than a frequency/time range. The term you replaced, "omfång", is the correct one.

For "Insert", I would use "Infoga" instead of "Klistra in" (which instead is the standard translation of "Paste").

"Ambigiös" is not a word, and "utmatning" should probably be replaced by "utsignal".

The rest looks fine.

**Comment by pauldavisthefirst** [comment]
Any plans to update this PR or respond to the comments? I'd love to merge this before 5.11 ....

**Comment by Umeaboy** [comment]
I'll look into it very soon. Hold on. :)

**Comment by Umeaboy** [comment]
I made the appropriate changes. I don't think I've missed anything. Who can merge?

**Comment by pauldavisthefirst** [comment]
manually rebased as 1d0221349. thanks!

**Pull request closed without merging**
