### PR TITLE
Finding ffmpeg

### PR DESCRIPTION
**Pull request by kiilerix**
Nice to have for 7.0 ...

### CODE REVIEW

**Comment by x42** [comment]
We cannot rely that a distro provided ffmpeg has a compatible commandline interfaces.

**Comment by x42** [comment]
I have manually applied the first part. Thanks!

**Comment by kiilerix** [comment]
> We cannot rely that a distro provided ffmpeg has a compatible commandline interfaces.

You still have the harvid versions as primary choice. That is what you and all users of your binary will rely on. This is just offering a fallback.

Also, on Windows it already searches much wider for system installed ffmpeg. This is just offering pretty much the same ting on Linux/Mac. Why is this change different?

**Comment by x42** [comment]
ffmpeg does not have a stable CLI interface, and it breaks regularly. Many versions do not work and we should not even try.  In addition to that, codecs and video-filters (required to add black lead in/out) are compile time options.

On Windows, the binaries we ship are named ffmpeg.exe and placed in a dedicated folder. However Ardour also needs to find the binaries if a user installs harvid or xjadeo independently from Ardour. A registry key is used for this.

Unlike Unices there is no global search path for binaries, that could lead to conflicting installations.

**Pull request closed without merging**
