### PR TITLE
added trackcolors to X-Touch, added _is_xtouch to device info

### PR DESCRIPTION
**Pull request by comgang**

### CODE REVIEW

**Comment by pauldavisthefirst** [comment]
Welcome to Ardour! If you can fix up the parens/line patterns in ::convert_color_to_xtouch_value() I'll be happy to merge this into master.

**Comment by comgang** [comment]
Thanks :) and thanks for your great work.

Like that? What's the convention?

**Comment by pauldavisthefirst** [comment]
Rebased and merged onto master. Thanks for the clean work.

**Comment by comgang** [comment]
Really cool :) So on to the next pull request. Thanks for merging

**Pull request merged**
