### PR TITLE
Windows build tweaks

### PR DESCRIPTION
**Pull request by renatolfc**
This PR contains a set of changes I had to make to the build tooling to enable compilation of Ardour 7.5 for Windows.

Of note, the script was referencing the old wavesaudio backend. I've replaced it with the portaudio backend.

Also, in the cowbuilder environment we were missing a few packages for successful packaging:
 * `ca-certificates`, for the calls to `curl`
 * `rsync` to copy some assets
 * `zip`/`unzip` for file extraction

### CODE REVIEW

**Comment by x42** [comment]
LZMA works fine for us. Since these scripts are used to create the official binaries it needs to remain enabled.

You can simply set 'QUICKZIP' env variable if needed.

**Comment by renatolfc** [comment]
Sounds good. I’ll update the PR.Apart from that, are the other changes appropriate?On 27 Jul 2023, at 17:52, Robin Gareus ***@***.***> wrote:﻿
LZMA works fine for us. Since these scripts are used to create the official binaries it needs to remain enabled.
You can simply set 'QUICKZIP' env variable if needed.

**Comment by x42** [comment]
I can cherry pick the other two commits. Unless @pauldavisthefirst does it, it will have to wait until early next week.

**Comment by renatolfc** [comment]
I think I can wait. Thanks for reviewing this and maintaining Ardour, @x42.

**Comment by x42** [comment]
Rebased and merged as 7.5-242 f4414c041a

Thank you!

**Pull request closed without merging**
