### PR TITLE
AAF protools files bug fix

### PR DESCRIPTION
**Pull request by agfline**
https://github.com/agfline/LibAAF/issues/28#issuecomment-2007541782

### CODE REVIEW

**Comment by x42** [comment]
I ran `tools/update_libaaf.sh` for the first commit (to address clang-format style).
Thanks for your hard work on this!

rebaesed and merged as 25397d781264ecc6

**Comment by agfline** [comment]
> I ran tools/update_libaaf.sh for the first commit (to address clang-format style).

I ran `tools/update_libaaf.sh` too for the initial commit, was formatting wrong ?

**Comment by x42** [comment]
Have you copied (or sym-linked) `tools/clang-format` to `.clang-format` in ardour's top-level folder?

**Comment by agfline** [comment]
Oops, my bad !
Thx Robin

**Pull request closed without merging**
