### PR TITLE
waf / wscript cleanup

### PR DESCRIPTION
**Pull request by kiilerix**
This adds consistency but shouldn't cause any functional change.

See the individual changesets and commit messages for clearest review, and cherry-pick any good parts.

### CODE REVIEW

**Comment by x42** [comment]
Looks good at a quick glance, and wow that's is a nice cleanup!

It's rather larger, so please allow for a few days to review it in full.

**Comment by kiilerix** [comment]
Thanks. Let me know if you have questions - I might have stared at it so long that I fail to see what isn't obvious.

**Comment by kiilerix** [comment]
@x42 - a gentle ping ;-)

**Comment by x42** [comment]
I still have a hard time to digest this. It's huge!
I would also have to test if it is compatible with python2 (macOS still ships that)

**Comment by kiilerix** [comment]
@pauldavisthefirst how about landing this now, after 8.0 has been released?

**Comment by pauldavisthefirst** [comment]
manually rebased and merged.

**Comment by pauldavisthefirst** [comment]
Alas, these changes broke the Windows builds:

https://nightly.ardour.org/i/A_WIN_x86_64/build_log.txt

We will try reverting "wscript: drop unnecessary str() on configure variable"

**Comment by x42** [comment]
Since the server's build-log is not persistent.  `waf configure` fails:
```
  File "/home/ardour/ardour-w64/.waf-2.0.26-44bc421a5f6bb452d70d83cbd5abc3fa/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "/home/ardour/ardour-w64/.waf-2.0.26-44bc421a5f6bb452d70d83cbd5abc3fa/waflib/Scripting.py", line 182, in run_commands
    ctx=run_command(cmd_name)
  File "/home/ardour/ardour-w64/.waf-2.0.26-44bc421a5f6bb452d70d83cbd5abc3fa/waflib/Scripting.py", line 173, in run_command
    ctx.execute()
  File "/home/ardour/ardour-w64/.waf-2.0.26-44bc421a5f6bb452d70d83cbd5abc3fa/waflib/Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "/home/ardour/ardour-w64/.waf-2.0.26-44bc421a5f6bb452d70d83cbd5abc3fa/waflib/Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/ardour/ardour-w64/.waf-2.0.26-44bc421a5f6bb452d70d83cbd5abc3fa/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/home/ardour/ardour-w64/wscript", line 1462, in configure
    set_compiler_flags (conf, Options.options)
  File "/home/ardour/ardour-w64/wscript", line 522, in set_compiler_flags
    if re.search ('x86_64-w64', conf.env['CC']) is not None:
  File "/usr/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer````

**Comment by x42** [comment]
I have reverted 615326be9b3ead774c8e399ffaa0879c1d8268ef to get builds going again.

**Pull request closed without merging**
