### PR TITLE
Details #2

### PR DESCRIPTION
**Pull request by 7890**
adapting to cruft removal in
c93bef0ab693021f0905420a7e004c67ab7d1fe8

### CODE REVIEW

**Comment by x42** [comment]
Rename as context menu in the track-header makes no sense to me. The action is already directly accessible there.

**Comment by 7890** [comment]
Many ways lead to Rome. "Rename" is missing in the context menu of the track header.

**Comment by 7890** [comment]
Let's discuss this for months

**Comment by 7890** [comment]
does anything speak against the tooltips?

**Pull request closed without merging**
