### PR TITLE
Feature/mackiepluginsubview

### PR DESCRIPTION
**Pull request by philsuess**
I extended the code in `libs/surfaces/mackie` (considerably) to enable the Plugin features described below.

### Main features: Plugin (Select & Edit)
1. Plugin Select: When a track is selected that has PluginInserts, pushing the "Plug-In" button on a mackie will list these across the strips. Clicking a vpot of a strip enables editing the parameters of this selected plugin.
2. Plugin Edit: When a Plugin is selected for editing, the input parameters of the plugin are shown across the channel strips and the vpot is assigned the corresponsing `AutomationControl` for the parameter.

#### Minor features
1. When the number of plugins or the number of parameters exceeds the number of strips available on the surface, one can flip through "pages" of views using the Cursor Left and Right keys (this logic I took from http://www.emagic.de/media/support/content/manuals/LogicControl_en.pdf)
2. When in the Plugin Select mode, rearranging the plugins in the mixer strip is reflected on the surface.
3. When in Plugin Edit mode, rearranging the plugins in the mixer strip still retains the edit view of the selected plugin (rearranging does not take away the current subview)
4. When removing a plugin in the mixer strip, this is reflected in Plugin Select, while the view jumps to Pan/Surround (the `None` subview) when in Plugin Edit mode.
5. Removing a track resets the subview to `None`
6. When in a Subview that is track-specific (`Track,` `EQ,` `Send,` `Plug-In,` `Inst`), selecting a different track retains the subview but updates the channel displays and vpot assignments accordingly. When in Plugin Edit mode for track A, and track B is selected, it changes to Plugin Select mode for track B (if plugins are present).

### Other fixes
1. Flip mode now works for `Send` and `Plugin` subviews
2. removed some unused variables and made small bug fixes here and there

### Implementation details
In order to more easily enable the Plugin feature, I implemented a Subview class which is responsible for handling all subview logic. This also allowed me to move a lot of code from strip.cc into the subclasses where I feel they belong. It is now very easy to add new features (say, Plugin Add or Remove) with this architechture: a new class inherits from the new Subview class and implements all logic pertaining to the subview. I adhered to what I understood to be the coding standards (from  ardour.org).

### Caveats and warnings
1. I obviously could not test the logic of `EQ` and `INST`` subviews because they are for Mixbus. I took really good care to only copy the code over to the subview classes and made **very** minor changes to the code there.
2. I was able to fully test the above mentioned features on my Behringer Xtouch with firmware 1.15. I do not own an extender, but I took care to write the code so that it should work for more than 8 strips.
3. I do not know what copyright statements to include for the two new files. I copied what was in strip.cc before because the new files contains code from there. 
4. For some time (ever since I updated to firmware 1.15??) I do not see any messages displayed by the method `MidiByteArray Surface::display_line (string const& msg, int line_num)`. I do see that they are formatted correctly, and I can catch them in a midi monitor app (the sysex is fine). However, my surface will not display anything - I will submit a bug on tracker and look into this myself). This observation is not specific to my changes. I observe it for version 5.12 and the current master  branch.

### Final notes
1. This is my first contribution to an open source project. Be direct (but also gentle).
2. It has been a blast and very rewarding coding in ardour and with the mackie surface in particular. I am open to receive requests from the dev team in this area.
3. I will volunteer gladly to do some work for the documentation - the manual is slim in the area of Mackie control units. Once (and if) this PR is accepted, I would start on that.

### CODE REVIEW

**Comment by pauldavisthefirst** [comment]
Phil - thanks a LOT for taking this on. I haven't looked at the code at all, but I had one immediate question: did you by any chance use the work that robin gareus already did for similar functionality in the maschine support code (even just as inpsiration?)

I ask because at some point this year or early next, i'd like to consolidate a lot of control surface code because there's too much duplication, and this will be easy the more is shared (or even, as now for a lot of stuff, copy-n-paste'd)

**Comment by philsuess** [comment]
> Phil - thanks a LOT for taking this on. I haven't looked at the code at all, but I had one immediate question: did you by any chance use the work that robin gareus already did for similar functionality in the maschine support code (even just as inpsiration?)
> 
> I ask because at some point this year or early next, i'd like to consolidate a lot of control surface code because there's too much duplication, and this will be easy the more is shared (or even, as now for a lot of stuff, copy-n-paste'd)

I have not. I was not aware of it. I noticed a lot of duplication as well and think there is lots of room for consolidation. In short: no, I only tried to improve on what was in the mackie code already.

**Comment by philsuess** [comment]
Do you mean the code in lib/surface/maschine2? I don’t see the plugin support there. Or did you mean the design itself? It looks very structured using the generic request interface. Mackie Code would benefit from this...

**Comment by x42** [comment]
I think he meant Faderport8/16. The Protocol is very Mackie like, with only a few special cases for the colored LEDs and scribble strips.

**Comment by philsuess** [comment]
@×42: You mentioned Rust being a candidate for surfaces code in the discourse forum. Is there a specific plan? As I said, I'm willing to do some free coding on the side.

**Comment by x42** [comment]
No specific plan. I was thinking of old NI-Machine interface where wrl wrote some driver in rust.

In any case it won't happen before Ardour 7 or 8. We currently (Ardour 6) support still support systems without a rust compiler (e.g OSX 10.5 PPC).

**Comment by pauldavisthefirst** [comment]
phil - i'd like to merge this before 6.0. Do you have time to address the merge conflicts?

**Comment by philsuess** [comment]
I just tried to rebase the feature branch on the current Ardour:master. But I must have not done it right. Any pointers?

**Comment by pauldavisthefirst** [comment]
Your rebase is just too old at this point.   Things have changed enough since January that there are conflicts now, that require manual resolution.

**Comment by philsuess** [comment]
I don't understand this and don't know how to proceed. I see that it says there are conflicts right here. Here is what I did on my local machine
1. fetched all changes from upstream (the Ardour/ardour repo)
2. rebased philsuess/ardour:master onto Ardour/ardour:master
3. rebased philsuess/ardour:feature/... branch onto philsuess/ardour:master
4. pushed the feature branch.

When I compare branches in github I get this (where it says "able to merge"):

Screenshot_2020-03-26_23-57-44

Should I copy the 9 files I changed locally, remove everything and start with a fresh fork?

**Comment by philsuess** [comment]
Screenshot_2020-03-27_00-18-32

**Comment by pauldavisthefirst** [comment]
paul@ryzen[1188]>ghm philsuess:feature/mackiepluginsubview
Switched to a new branch 'philsuess-feature/mackiepluginsubview'
remote: Enumerating objects: 351, done.
remote: Counting objects: 100% (326/326), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 301 (delta 247), reused 269 (delta 215), pack-reused 0
Receiving objects: 100% (301/301), 45.13 KiB | 15.04 MiB/s, done.
Resolving deltas: 100% (247/247), completed with 18 local objects.
From https://github.com/philsuess/ardour
 * branch                  feature/mackiepluginsubview -> FETCH_HEAD
Updating f744b5fc12..bd85d7b0f9
Fast-forward
 libs/surfaces/mackie/mackie_control_protocol.cc |  163 +++--------------
 libs/surfaces/mackie/mackie_control_protocol.h  |   22 +--
 libs/surfaces/mackie/mcp_buttons.cc             |   30 ++-
 libs/surfaces/mackie/strip.cc                   |  622 +++++----------------------------------------------------------
 libs/surfaces/mackie/strip.h                    |   21 +--
 libs/surfaces/mackie/subview.cc                 | 1233 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 libs/surfaces/mackie/subview.h                  |  279 ++++++++++++++++++++++++++++
 libs/surfaces/mackie/subview_modes.h            |   39 ++++
 libs/surfaces/mackie/wscript                    |    1 +
 9 files changed, 1664 insertions(+), 746 deletions(-)
 create mode 100644 libs/surfaces/mackie/subview.cc
 create mode 100644 libs/surfaces/mackie/subview.h
 create mode 100644 libs/surfaces/mackie/subview_modes.h
Current branch philsuess-feature/mackiepluginsubview is up to date.
First, rewinding head to replay your work on top of it...
Applying: list plugininserts on mackie
Applying: show plugin ui on vpot press
Applying: rename mackie subview mode to PluginSelect
Applying: refactor subviews into strategy pattern
Applying: refactor trackview subview notify and setup
Applying: cleanup of refactored functions
Applying: move eq subview to its own class
Applying: move dynamics subview to its own class
Applying: move sends and pluginselect subviews to its own classes
Applying: small fixes
Applying: move vselect_event subview logic to subview classes
Applying: switch to plugin subview state
Applying: hook up plugin parameters
Applying: implement parameter banking
Applying: remove unused connections
Applying: change tabs to spaces in wscript
Applying: refactor
Applying: fix flip mode for plugin assign
Applying: fix subview logic when selecting a different track
Applying: reset vpot controls when subview is deleted
Applying: deselect track -> set subview to None
Applying: make plugin selection react to reordered and deleted plugins
Applying: make PluginEdit failsafe
Applying: list plugininserts on mackie
Using index info to reconstruct a base tree...
M	libs/surfaces/mackie/mackie_control_protocol.cc
M	libs/surfaces/mackie/mackie_control_protocol.h
M	libs/surfaces/mackie/mcp_buttons.cc
M	libs/surfaces/mackie/strip.cc
M	libs/surfaces/mackie/strip.h
.git/rebase-apply/patch:10: trailing whitespace.
		
.git/rebase-apply/patch:100: trailing whitespace.
	
.git/rebase-apply/patch:115: trailing whitespace.
	
.git/rebase-apply/patch:117: trailing whitespace.
	
.git/rebase-apply/patch:140: trailing whitespace.
	
warning: 5 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging libs/surfaces/mackie/strip.h
CONFLICT (content): Merge conflict in libs/surfaces/mackie/strip.h
Auto-merging libs/surfaces/mackie/strip.cc
CONFLICT (content): Merge conflict in libs/surfaces/mackie/strip.cc
Auto-merging libs/surfaces/mackie/mcp_buttons.cc
CONFLICT (content): Merge conflict in libs/surfaces/mackie/mcp_buttons.cc
Auto-merging libs/surfaces/mackie/mackie_control_protocol.h
CONFLICT (content): Merge conflict in libs/surfaces/mackie/mackie_control_protocol.h
Auto-merging libs/surfaces/mackie/mackie_control_protocol.cc
CONFLICT (content): Merge conflict in libs/surfaces/mackie/mackie_control_protocol.cc
Recorded preimage for 'libs/surfaces/mackie/mackie_control_protocol.cc'
Recorded preimage for 'libs/surfaces/mackie/mackie_control_protocol.h'
Recorded preimage for 'libs/surfaces/mackie/mcp_buttons.cc'
Recorded preimage for 'libs/surfaces/mackie/strip.cc'
Recorded preimage for 'libs/surfaces/mackie/strip.h'
error: Failed to merge in the changes.
Patch failed at 0024 list plugininserts on mackie
hint: Use 'git am --show-current-patch' to see the failed patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

Rebase failed

**Comment by pauldavisthefirst** [comment]
The previous output comes doing this:

```
git checkout -b $developer-$branch master || die "New branch failed"
git pull https://github.com/$developer/ardour.git $branch || die "Pull failed"
git rebase master || die "Rebase failed"
git checkout master || die "Checkout master failed"
git merge $developer-$branch || die "Merge failed"
git branch -d $developer-$branch || die "Removing remote branch failed"

```

**Comment by philsuess** [comment]
Paul, check out PR #481. It's the identical change set. Let's close this one here if it's OK with you guys.

**Comment by philsuess** [comment]
Close as duplicate to #481.

**Pull request closed without merging**
