### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell`

### CODE REVIEW

**Comment by pauldavisthefirst** [comment]
gtk2_ardour/configuration_metadata.h is a generated file and should not be edited or part of a pull request. Fixes go into preferences_metadata and will propagate from there.

**Comment by luzpaz** [comment]
Reverted file.  
Rebased and force pushed.

**Comment by luzpaz** [comment]
should be ready for merge

**Comment by pauldavisthefirst** [comment]
manually rebased & merged, thanks.

**Pull request closed without merging**
