### PR TITLE
Added support to set gain automation by OSC.

### PR DESCRIPTION
**Pull request by johannes-mueller**
Added support for OSC message

"/ardour/routes/gain_automation" rid state

where rid is the remote route id and state is a character representing
the desired gain automation state:

'm': Manual (Off)
'p': Play
'w': Write
't': Touch

### CODE REVIEW

**Comment by x42** [comment]
ideally there'd be an API to control all automatables - not just fader-gain.

**Comment by johannes-mueller** [comment]
I will look into this after new year.

**Comment by x42** [comment]
having a 2nd look.. the faders are special-cased in routes anyway.

the only common part with generic plugin controls would be the switch {} statement
for `boost::shared_ptr<AutomationControl>`

what do you think of

```
static void set_automation_state (boost::shared_ptr<AutomationControl> c, char state)
{
switch (state) ....
}

OSC::route_set_gain_automation (int rid, char state)
{
  if (!session) { return -1;}
  boost::shared_ptr<Route> r = session->route_by_remote_id (rid);
  if (!r || !r->gain_control ()) { return -1; }
  set_automation_state (r->gain_control (), state);
}
```

**Comment by johannes-mueller** [comment]
Sounds sensible to me.

Unfortunately I won't have time to hack on this before January. I will leave the PR open though. Maybe other people come up with some more clever ideas.

**Comment by johannes-mueller** [comment]
New PR with same functionality #225 ...

**Pull request closed without merging**
