### PR TITLE
Fix man page encoding

### PR DESCRIPTION
**Pull request by nphilipp**
French and Russian man pages were still encoded in ISO-8859-1 and KOI8-R, respectively, instead of UTF-8.

### CODE REVIEW

**Comment by pauldavisthefirst** [comment]
Not 100% sure about these changes. Need to consult/read around more before pulling.

**Comment by nphilipp** [comment]
I think it's good to only use UTF-8 encoding, converting to other encodings is straight-forward and doesn't involve guesswork (like if the Russian man page is in ISO-8859-5 or KOI8-R).

**Comment by nphilipp** [comment]
@prokoudine, was there a special reason to originally use KOI8-R encoding for the Russian version of the manpage, other than that it was prevalent at the time?

**Comment by prokoudine** [comment]
Prevalent at the time.

**Comment by pauldavisthefirst** [comment]
manually rebased and merged to master. thanks!

**Pull request closed without merging**
