### PR TITLE
Add Sun backend option for JACK

### PR DESCRIPTION
**Pull request by niacat**
JACK's Sun backend is used on NetBSD, illumos, GNU/HURD (?), others (?).

### CODE REVIEW

**Comment by pauldavisthefirst** [comment]
I'd prefer to see the basic conditionals that make this available be wrapped in compile-time OS ident #ifdefs

**Comment by niacat** [comment]
It's not really OS-specific since it's available through rump, but yeah I can do this.

**Comment by krytarowski** [comment]
sun backend is OS independent.

**Comment by pauldavisthefirst** [comment]
It is not OS independent. It uses ioctl's that are OS dependent.

**Comment by krytarowski** [comment]
These ioctls can be rump syscalls (hypercalls). rump is a NetBSD kernel built as a literal standalone library. It can be executed in userland on Windows, Linux, Darwin, inside a bootloader in HURD etc. No need for real syscall ioctls. rump runs in theory on anything more or less with a C99/C11 compiler.

**Comment by pauldavisthefirst** [comment]
That maybe true, but that would in turn require different build options for JACK on the non-Sun-ish/BSD host platform, since the configure time check is for the presence of sys/audioio.h (JACK1) and/or python's sys.platform saying "sunos" (JACK2).

Ardour's "JACK configuration" options are absolutely not intended to be all-encompassing. There are other JACK front-ends that can and should be used for unusual situations. If you're running on Linux, the "sun" driver for JACK is not a sensible option to present to users.

**Comment by niacat** [comment]
In any case, can we get this merged? It's only going to show up on platforms where it's the primary audio API baked into the kernel, in the current state of this PR.

**Comment by pauldavisthefirst** [comment]
manually rebased and merged. thanks!

**Pull request closed without merging**
