### PR TITLE
update german translation

### PR DESCRIPTION
**Pull request by edogawa23**

### CODE REVIEW

**Comment by jeythekey** [comment]
May I make a quick suggestion (instead of creating a new issue for this):
Currently, the drop-down menu of the edit mode button (slide, ripple, lock) has no German translation. The label shown on the button itself (after selection) is translated, though. Would thus probably be an easy fix?
I also found [this](https://tracker.ardour.org/view.php?id=7924) today, maybe that can also be fixed in this PR?

Thanks!

**Comment by edogawa23** [comment]
@jeythekey thanks for your feedback, it's all there now... the strings mentioned in the Mantis issue have changed a bit since 5.12, and for now I preferred to keep a literal translation, maybe Paul or Robin will consider changing the source string to mention edit point...

**Comment by x42** [comment]
Thank you both! -- rebased and merged as 6.0-189 d0681f8013

I'll have a look at https://tracker.ardour.org/view.php?id=7924 later today.

**Comment by jeythekey** [comment]
Thanks to @edogawa23 also from my side, that was probably one of the fastest fixes I encountered so far ;)

**Pull request closed without merging**
