### PR TITLE
Sort plugins by name (label) in the preset combo selection

### PR DESCRIPTION
**Pull request by enorrmann**

### CODE REVIEW

**Comment by x42** [comment]
This used to be the case in the past. In 4e1464e70fc73b this was intentionally reverted, and factory presets are ordered in the way the vendor specifies.  This change was motivated for plugins that have many presets that are nicely grouped.

The general sort order is: factory presets as ordered by the vendor, then user-presets, ordered by name.

PS. Since control-surfaces also allow access to plugin-presets, the change has to be done in the backend (not the GUI).
Although the GUI could offer an option to sort by label.

**Comment by enorrmann** [comment]
> then user-presets, ordered by name

Well it seems that this is not the case (as far as I understand).
I have several custom saved presets and they are displayed (apparently) randomly at the gui, or may be sorted by creation date, I'm not sure... but definitively not by name.

**Comment by x42** [comment]
Which plugin standard? AU? LV2?

**Comment by enorrmann** [comment]
VST... same happens in the "favorite plugins" explorer 
https://i.imgur.com/1oekOMG.png

**Pull request closed without merging**
