### PR TITLE
fixed compilation on osx, minimal version was wrong

### PR DESCRIPTION
**Pull request by powerpaul17**

### CODE REVIEW

**Comment by x42** [comment]
XCode usually 1 version backwards compatible. e.g. on 10.11, there's still the 10.10 SDK.

I suppose the actual issue is the common handling of [ 'mavericks', 'yosemite', 'el_capitan' ] in this case. Then again current wscript works for me as-is on Yosemite (10.10.5) and I know there are some compiling it on El Capitan without changes.

What version of OSX or macOS and XCode are you using?

**Comment by powerpaul17** [comment]
I am on "Sierra" (10.12) and I had problems with some unavailable header files, unfortunately I can't remember now which ones exactly. I just noticed, that in the other cases (lion, etc) "-mmacosx-version-min" always corresponded to the actual minimal version of the case.

**Comment by powerpaul17** [comment]
Maybe it requires adding an additional case for "Sierra" in which the minimal version is 10.9

**Comment by pauldavisthefirst** [comment]
that would be better, in my opinion.

**Comment by powerpaul17** [comment]
ok, I adapted the respective portions of the wscript.

**Comment by pauldavisthefirst** [comment]
manually rebased and merged.

**Pull request closed without merging**
