### PR TITLE
Updated Italian translation

### PR DESCRIPTION
**Pull request by aFunkyBass**
A lot of translations added, but still not complete especially the Cue page which needs extra work on nomenclature.

### CODE REVIEW

**Comment by Daniele71** [comment]
I tested the translation and it's ok even if not complete. It's a big step ahead, so add to 8.7 please.

**Comment by aFunkyBass** [comment]
Hello! Is there any issue with this pull request? It's my first time so I don't know if there's something wrong... :)

**Comment by pauldavisthefirst** [comment]
Manually rebased and merged, thanks!

**Comment by pauldavisthefirst** [comment]
Do you have a "regular name" that I can use in the credits?

**Comment by aFunkyBass** [comment]
Yes, sure I'm always too lazy update my profile, but I'll do it right now. Anyway my name is Guido Pietrella. Please also credit @Daniele71 which helped with this translation.
Thanks.

**Comment by Daniele71** [comment]
@pauldavisthefirst Profile updated, thanks.

**Pull request closed without merging**
