### PR TITLE
Update blueberry_milk-ardour.colors

### PR DESCRIPTION
**Pull request by cooltehno**
Hi! (NEXT attempt)
++more contrasting&bright (compared with existing theme). Added comments to < Color > section.
video (with comparison):
https://vimeo.com/416166712

### CODE REVIEW

**Comment by cooltehno** [comment]
In the original file there was an excess line (176) - deleted in new version:
```
176 <ColorAlias name="lua action button: fill" alias="theme:bg"/>
177<ColorAlias name="lua action button: fill" alias="widget:bg"/>
```

**Comment by pauldavisthefirst** [comment]
just asking why your other PRs were closed? did i miss something?

**Comment by cooltehno** [comment]
If about PRs of 2018year - they  were ignored (as I understood because of new fundamentals of Ardour structure) The files had an old structure and Ben Loftis deleted some overloading color slots from the palette, so I've deleted these PRs. 

This year PRs - I commented in PRs:
"I've closed it because in my changes I've deleted all the comments (in color definition lines). Also need some checking about some "alert: greenish" color. Sorry"

Also I wrote a new comment to discussion here:
https://github.com/Ardour/ardour/commit/7058a8074fa7d8778e30ef2e0adbe5e69f179d63#diff-821fd0bff6860a19c0161bc5ca6c37a2

**Comment by pauldavisthefirst** [comment]
manually merged&rebased. thanks!

**Pull request closed without merging**
