### PR TITLE
Turn PinMappings class into a type alias

### PR DESCRIPTION
**Pull request by aledomu**

### CODE REVIEW

**Comment by x42** [comment]
At some point in time there was the idea to add Lua Bindings for PinMappings, in which case a class is preferable, so I kept it.

**Comment by x42** [comment]
Then again we can always revert it back to a class later. So far there's no reason to directly expose it.

**Comment by aledomu** [comment]
I thought the original intent was only to extend the original class over its shortcomings at its time. If bindings are planned, then a type alias communicates the wrong intent for the future. Closing.

**Comment by x42** [comment]
On 2nd thought, I was thinking to merge  it anyway, and revert it to a class when needed.

**Comment by aledomu** [comment]
There you have it again to cherry-pick

**Comment by x42** [comment]
Rebased and merged as 8.6-499 e48d97ed69
Thanks!

**Pull request closed without merging**
