### PR TITLE
autowaf: fix escaping with Python 3.12

### PR DESCRIPTION
**Pull request by tartina**

### CODE REVIEW

**Comment by kiilerix** [comment]
LGTM - very nice to have for Ardour 8, for example for Fedora.

But also, this is in a part of autowaf that Ardour doesn't seem to use. It is unfortunate that Ardour has to maintain it. Ardour should either strip autowaf down to the bare minimum that actually is used, or blindly vendor an upstream version. It would perhaps be better to remove this chunk than to fix it.

**Comment by x42** [comment]
We should just remove `make_simple_dox`. it's not used at all.

**Comment by kiilerix** [comment]
> We should just remove `make_simple_dox`. it's not used at all.

Agreed - that seems like a very good solution too. It would be nice to minimize the surface we have to maintain. Unless we want to rebase to a new upstream version and leave all maintenance to upstream?

**Comment by pauldavisthefirst** [comment]
I removed the offending method from autowaf.py, and upgraded waf to 2.0.26 (from 2.0.23).

**Pull request closed without merging**
