### PR TITLE
remove parenthesis from the disabled track name

### PR DESCRIPTION
**Pull request by iurienistor**
I propose to remove parenthesis from the disabled track name.

### CODE REVIEW

**Comment by pauldavisthefirst** [comment]
there needs to some visual indication of inactive status

**Comment by iurienistor** [comment]
> there needs to some visual indication of inactive status

Ok. Maybe a grey out text instead of parenthesis. But since I am still familiarizing with the code... I couldn't find how to user the grey from the theme colors.

**Comment by pauldavisthefirst** [comment]
You can't use "grey". You can get a color by name, and it should preferably be functional name, not an actual color name. UIConfig::color ()

Actually using it generally harder.

**Comment by iurienistor** [comment]
@pauldavisthefirst I don't know if it is the exact file but in themes/dark-ardour.colors there are defined aliases <ColorAliases> and <Colors> used by aliases. There is widget:gray color, but I am afraid it is not intended to be used as "grayout color" in <ColorAliases>. Also, I don't see anything related to track label name in the <ColorAliases>. Do I need to add it there and define also a new color for gray out stuff?...

**Comment by x42** [comment]
What's wrong with using braces? That leaves the name clearly visible, while still providing an indication.

**Comment by iurienistor** [comment]
@x42 My intention was to remove parenthesis and grayout. I thought usually in GUI when something is disabled everything is just grayed out but I am not aware of Ardour specifications.

**Comment by x42** [comment]
Usually only actions that are sensitive are made insensitive (aka grayed out) when they re not available.

Easiest way to mark it grayed-out is:
```
inactive_label.set_sensitive (false);
```

**Comment by iurienistor** [comment]
@x42 I've just tested, the contrast unfortunately is bad. I think probably it should be used in the combination with colors defined in the themes that will overwrite the widget styles.

**Pull request closed without merging**
