### PR TITLE
Typo in code and comments paramater

### PR DESCRIPTION
**Pull request by BrunoVernay**
paramater / parameter
In C code, Lua code and comments.  Searched through the whole repo, but not tested ...
It is a tiny subset of #627 !  Eventually, I could slowly distill #627 in separate PR as they are merged. If code is impacted I could build the thing but I guess some kind of automation rebuilds Ardour for each commit

### CODE REVIEW

**Comment by x42** [comment]
`libs/appleutility` is unmodified upstream code from Apple -- best leave that alone (or file an issue upstream)

Also we generally prefer to split changes to `lib/*` and `gtk2_ardour/*` into separate commits.

**Comment by BrunoVernay** [comment]
3 commits
- gtk2_ardour/ (Comments)
- libs/ (Code!)
- Lua (Comments)

I removed Apple stuff.

**Comment by x42** [comment]
Thanks! rebased and merged as 7.0-pre0-1145-g157af3ac4f

**Comment by BrunoVernay** [comment]
On a Sunday? Works of passion ...

**Pull request merged**
