### PR TITLE
Feature7581 recent plugins

### PR DESCRIPTION
**Pull request by relascope**
http://tracker.ardour.org/view.php?id=7581

Implementation details:
Plugins sorted alphabetically to keep integrity with Recent-Session view. 
New Configuration variable max-recent-plugins.

No additional handling like sorting out Favorites like requested.

### CODE REVIEW

**Comment by relascope** [comment]
changed to use XML-format.

I'm a bit concerned about `Route::add_processors()`as it is also called, when loading a session (with plugins), so it will screw up my _actually_ used last plugin.

**Comment by relascope** [comment]
Sry, don't know the exact machanics what is/has to be done, when loading a session, but my callstack for loading a session registers a call to `Route::add_processors`. 
So without changing the loading, it would screw up the recent list. 
At the time of writing I didn't dig into the loading logic, so no further changes right now...

```
#0  0x00007ffff6706f40 in ARDOUR::Route::add_processors(std::__cxx11::list<boost::shared_ptr<ARDOUR::Processor>, std::allocator<boost::shared_ptr<ARDOUR::Processor> > > const&, boost::shared_ptr<ARDOUR::Processor>, ARDOUR::Route::ProcessorStreams*)@plt () at ./../build/libs/ardour/libardour.so.3
#1  0x00007ffff6d6297d in ARDOUR::Route::add_processor(boost::shared_ptr<ARDOUR::Processor>, boost::shared_ptr<ARDOUR::Processor>, ARDOUR::Route::ProcessorStreams*, bool) (this=0x55555cbe7bb0, processor=..., before=..., err=0x0, activation_allowed=true) at ../libs/ardour/route.cc:861
#2  0x00007ffff6d62658 in ARDOUR::Route::add_processor(boost::shared_ptr<ARDOUR::Processor>, ARDOUR::Placement, ARDOUR::Route::ProcessorStreams*, bool) (this=0x55555cbe7bb0, processor=..., placement=ARDOUR::PostFader, err=0x0, activation_allowed=true) at ../libs/ardour/route.cc:831
#3  0x00007ffff6d5e48b in ARDOUR::Route::init() (this=0x55555cbe7bb0)
    at ../libs/ardour/route.cc:191
#4  0x00007ffff6e632d2 in ARDOUR::Session::XMLRouteFactory(XMLNode const&, int) (this=0x55555788f000, node=..., version=5990)
    at ../libs/ardour/session_state.cc:1840
#5  0x00007ffff6e62b5e in ARDOUR::Session::load_routes(XMLNode const&, int) (this=0x55555788f000, node=..., version=5990)
    at ../libs/ardour/session_state.cc:1770
#6  0x00007ffff6e61be4 in ARDOUR::Session::set_state(XMLNode const&, int) (this=0x55555788f000, node=..., version=5990) at ../libs/ardour/session_state.cc:1670
#7  0x00007ffff6e5799f in ARDOUR::Session::post_engine_init() (this=0x55555788f000) at ../libs/ardour/session_state.cc:297
```

**Comment by x42** [comment]
This is not a plugin, it's a processor (the Fader). and it's called whenever a track is created (along with other built-in process0rs)

**Comment by x42** [comment]
Anyway, I can take care of this someday. There's also  feature-request to also collect plugin-usage (opt-in) statistics.

**Comment by x42** [comment]
This was just implemented as 2685728f59c and 0eb038575f for 6.0.169

**Pull request closed without merging**
