### PR TITLE
Adhere more to code style guide

### PR DESCRIPTION
**Pull request by 7890**
-Use tab for indentation
-Use curly braces for if / while

### CODE REVIEW

**Comment by x42** [comment]
Wow, that's nice! 

It'd be great to consolidate those into 2 commits (`libs/`  `gtk2_ardour/`) don't clutter up the history and lengthen `git bisect` runs for  whitespace NO-OP changes.

**Comment by 7890** [comment]
i'd like the moon to be out of cheese, it would be great!

**Comment by pauldavisthefirst** [comment]
if you don't want to do that, then tell us the workflow you used to
generate this commit and we'll do it ourselves, without snark.

snark on IRC is great, snark on GH's PR system is just irritating.

**Comment by x42** [comment]
It cannot be merged anyway, there is no public remote repository. Github says "patch is too large and not available).

**Comment by 7890** [comment]
please see #357, it's now all in one commit. does that help?

**Comment by x42** [comment]
Yes that does help, see discussion there.  As for the libs, a nice way to solve this would be to use *this* branch as-is.   `git reset`  (no --hard, just the index) to the last upstrem version.  `git add libs/ardour libs/pbd libs/gtkmm2ext`  and commit.

Note that 3rd party libs (vamp, qm-dsp, libltc etc  are not covered by ardour's coding-style) we try to stay close to upstream for those.

**Comment by 7890** [comment]
Paul, the workflow was to grep for multiple spaces and open each file, go through it and decide whether or not the spaces are valid (to align stuff) or in place where a tab was expected. I could have missed some, i'd say roughly 95% of obvious tab cases are catched. the alignment of multi-line statements needs a second round, i've touched some but not systematically (i.e. tab up to indentation of statement, then use space to align to method ()). it's a start..

**Comment by 7890** [comment]
x42, i've not touched any other files than in /gtk2_ardour/*.
it needs a separate round for /libs/*

**Comment by x42** [comment]
My bad, for some reason I though some of those "diff to large" referenced lib/*
Anyway I'll close this #357  supersedes this PR. Thanks!

**Pull request closed without merging**
