### PR TITLE
NO-OP whitespaces, curly braces (/gtk2_ardour/*)

### PR DESCRIPTION
**Pull request by 7890**
same as PR #355 but all in one commit.

### CODE REVIEW

**Comment by x42** [comment]
Thanks.  I'm currently looking though it with `git diff -w` (ignore whitespace changes). I hoped that would come up empty but it doesn`t.

**Comment by 7890** [comment]
ok here's what i did: 
-new ardour fork, checkout
-copy all 132 changed files over to fork (the 132 files are valid for 773c31afc070caeaa3753bfdbbe818339884ae54)
-commit all and push

the following message could give a hint:
```
$ git commit -am "NO-OP whitespaces, curly braces (/gtk2_ardour/*)"
[master 2e603c2] NO-OP whitespaces, curly braces (/gtk2_ardour/*)
 132 files changed, 3292 insertions(+), 3294 deletions(-)
 rewrite gtk2_ardour/engine_dialog.h (63%)
 rewrite gtk2_ardour/midi_channel_selector.h (70%)
 rewrite gtk2_ardour/nsmclient.cc (70%)
 rewrite gtk2_ardour/nsmclient.h (67%)

```
i think it did merge things with changes that were done since 773c31afc070caeaa3753bfdbbe818339884ae54

how to git that?

**Comment by x42** [comment]
Yeah looks like you've manually copied files.  Anyway I'll fix it up.

**Comment by 7890** [comment]
ah.

**Comment by x42** [comment]
Fixup: re-applying the change: `git show 2b1b0aa240f | patch  -p1 ; git commit --amend` does seem to do the trick. 

I'll the rest and merge/push in a bit.

**Comment by 7890** [comment]
just be sure that the commit(s) will show up as my contribution not yours, can you do that?

**Comment by x42** [comment]
yes, git will make sure of that.

**Comment by x42** [comment]
Rebased/merged+fixed as Ardour 5.10-171 63ea7b651
Thanks a lot!

**Pull request closed without merging**
