### PR TITLE
Make menu item/action for opening Add Track/Bus/VCA dialog consistent with window title.

### PR DESCRIPTION
**Pull request by trebmuh**
consistency with the window's title

### CODE REVIEW

**Comment by mojofunk** [comment]
The change itself looks fine. The commit message is not acceptable IMO, Something like:

Make menu item/action for opening Add Track/Bus/VCA dialog consistent with window title.

Would be fine.

**Comment by trebmuh** [comment]
That was an automatic one.
Changed as requested now.

**Comment by mojofunk** [comment]
Sorry for the delay in getting back to you on this, thanks for making that change.

Looks good to me. Approved.

**Comment by mojofunk** [comment]
Actually, it seems you just changed the title of the PR but not the commit message.

I've changed it locally can pushed to master branch. Thanks.

This PR can now be closed.

**Comment by trebmuh** [comment]
Thanks. :+1:

**Pull request closed without merging**
